name: Build sifli-hal & examples

on:
  push:
    branches: [ "main" ]
    paths:
      - 'sifli-hal/**'
      - 'examples/**'
      - '.github/workflows/build-hal.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'sifli-hal/**'
      - 'examples/**'
      - '.github/workflows/build-hal.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install rust targets, linker
      run: |
        rustup target add thumbv8m.main-none-eabi
        rustup target add thumbv8m.main-none-eabihf
        cargo install flip-link
    - name: Build sifli-hal sf32lb52x
      run: |
        cd sifli-hal
        cargo update
        cargo build --verbose --features "sf32lb52x rt defmt" --target thumbv8m.main-none-eabi
        cd $GITHUB_WORKSPACE
    - name: Check sifli-hal
      run: |
        cd sifli-hal
        cargo update
        cargo test --no-default-features --features="sf32lb52x time"
        cd $GITHUB_WORKSPACE
    - name: Build Examples
      run: |
        for d in $(ls -1 ./examples); do
          if [ -f "./examples/$d/Cargo.toml" ]; then
            (cd ./examples/$d && cargo update && cargo build --release)
          fi
        done
        cd $GITHUB_WORKSPACE
